version: "3.8"

services:
  authservice:
    build:
      context: .
      dockerfile: LocacaoVeiculos.AuthService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq

  paymentservice:
    build:
      context: .
      dockerfile: LocacaoVeiculos.PaymentService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq

  rentalservice:
    build:
      context: .
      dockerfile: LocacaoVeiculos.RentalService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq

  vehicleservice:
    build:
      context: .
      dockerfile: LocacaoVeiculos.VehicleService/Dockerfile
    ports:
      - "5004:80"
    depends_on:
      - rabbitmq

  apigateway:
    build:
      context: .
      dockerfile: LocacaoVeiculos.ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - authservice
      - paymentservice
      - rentalservice
      - vehicleservice

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # Porta para a conexão AMQP
      - "15672:15672" # Porta para o painel de administração
