services:
  eureka-server:
    container_name: eureka-server
    image: steeltoeoss/eurekaserver:latest
    restart: on-failure
    hostname: eureka-server
    networks:
      - locacao-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    hostname: rabbitmq
    ports:
      - "5672:5672" # Porta para a conexão AMQP
      - "15672:15672" # Porta para o painel de administração
    networks:
      - locacao-network

  apigateway:
    build:
      context: .
      dockerfile: ./LocacaoVeiculos.ApiGateway/Dockerfile
    hostname: apigateway
    networks:
      - locacao-network

  authservice:
    build:
      context: .
      dockerfile: ./LocacaoVeiculos.AuthService/Dockerfile
    hostname: authservice
    networks:
      - locacao-network

  paymentservice:
    build:
      context: .
      dockerfile: ./LocacaoVeiculos.PaymentService/Dockerfile
    hostname: paymentservice
    networks:
      - locacao-network

  vehicleservice:
    build:
      context: .
      dockerfile: ./LocacaoVeiculos.VehicleService/Dockerfile
    hostname: vehicleservice
    networks:
      - locacao-network

  rentalservice:
    build:
      context: .
      dockerfile: ./LocacaoVeiculos.RentalService/Dockerfile
    hostname: rentalservice
    networks:
      - locacao-network

networks:
  locacao-network:
    driver: bridge
