version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # Porta para a conexão AMQP
      - "15672:15672" # Porta para o painel de administração
    networks:
      - locacao-network

  authservice:
    build:
      context: ./AuthService
    ports:
      - "5001:80"
    networks:
      - locacao-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  paymentservice:
    build:
      context: ./PaymentService
    ports:
      - "5002:80"
    networks:
      - locacao-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  vehicleservice:
    build:
      context: ./VehicleService
    ports:
      - "5003:80"
    networks:
      - locacao-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rentalservice:
    build:
      context: ./RentalService
    ports:
      - "5004:80"
    networks:
      - locacao-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  locacao-network:
    driver: bridge
